sudo: requried
services:
  - docker

before_install:
  - docker build -t pingc1/docker-react -f Dockerfile.dev .

install: travis_wait 30 mvn install

script:
  - docker run pingc1/docker-react npm run test -- --coverage

